# Generated by Django 4.2.16 on 2024-11-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lncsmd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tesiuy", models.BigIntegerField()),
                ("xswddv", models.BigIntegerField()),
            ],
        ),
    ]
